# Generated by Django 3.1.1 on 2020-09-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, null=True)),
                ('Stock_code', models.CharField(max_length=100)),
                ('Peer_group', models.CharField(choices=[('Pulp', 'Pulp'), ('Packaging', 'Packaging'), ('Graphics', 'Graphics'), ('Tissue', 'Tissue'), ('Flexibles', 'Flexibles'), ('Merchants', 'Merchants'), ('Flexibles', 'Flexibles')], default='Pulp', max_length=200)),
            ],
        ),
    ]
