# Generated by Django 3.0.3 on 2020-09-22 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_fx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='fx',
            options={'verbose_name_plural': 'FX'},
        ),
        migrations.CreateModel(
            name='Financial_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_capitalization_original', models.FloatField(max_length=50, null=True)),
                ('market_capitalization_euro', models.FloatField(max_length=50, null=True)),
                ('share_price_original', models.FloatField(max_length=50, null=True)),
                ('share_price_euro', models.FloatField(max_length=50, null=True)),
                ('shares_number', models.FloatField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Companies')),
            ],
            options={
                'verbose_name_plural': 'Financial_Data',
            },
        ),
    ]
