# Generated by Django 3.0.3 on 2020-10-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20201013_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peer_group_Financial_data',
        ),
    ]
