# Generated by Django 3.0.3 on 2020-10-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_peer_group_financial_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peer_group_Financial_data',
        ),
    ]
