# Generated by Django 3.0.3 on 2020-10-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_peer_group_financial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='Peer_group_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Peer_group_lists'),
        ),
    ]
