# Generated by Django 3.0.3 on 2020-10-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_remove_companies_peer_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='Peer_group_2',
            new_name='Peer_group',
        ),
    ]
