# Generated by Django 3.0.3 on 2020-12-30 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20201013_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peer_group_financial_data',
            options={'verbose_name_plural': 'Peer_group_Financial_data'},
        ),
        migrations.AlterField(
            model_name='peer_group_financial_data',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
